%{
    This handle class decodes an image using the decryption key returned
    by the encoder class
%}
classdef SteganographicDecoder < handle
    properties
        ImageName  % The name of the image to be used
        Valid % Logical value to confirm that the image is valid
        ImageData % The pixel data of the image
        DecryptionKey % Locations of all of the bytes that were encoded
        MessageLength % The length of the message
    end
    methods
 
        %{
            Constructor
        %}
        function obj = SteganographicDecoder(filename, key_name)
            obj.DecryptionKey = key_name;
            obj.ImageName = filename;
        end
        %{
            Check the file prefix to confirm that it was generated by the
            GanoGraphic encoder
        %}
        function checkFile(obj)
            msgID = 'checkFile:invalidImage';
            msg = strcat(obj.ImageName, ' is not a GanoGraphic image.');
            InvalidGanoImageException = MException(msgID, msg);
            if strcmp(strtok(obj.ImageName, '-'), 'Gano') == 0
               throw(InvalidGanoImageException)
            else
                obj.Valid = 1;
            end
        end
        %{
            Load the steganography
        %}
        function loadSteganography(obj)
            obj.ImageData = imread(obj.ImageName);
        end
        %{
            Load the decryption key
        %}
        function loadDecryptionKey(obj)
            load(obj.DecryptionKey);
        end
        
    end    
end